// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NguyenVanAn0025.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230623013334_Create_ForeignKey_NVA025New")]
    partial class Create_ForeignKey_NVA025New
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("NguyenVanAn0025.Models.NVA025New", b =>
                {
                    b.Property<int?>("NewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewMa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("TEXT");

                    b.HasKey("NewID");

                    b.HasIndex("TenSanPham");

                    b.ToTable("NVA025New");
                });

            modelBuilder.Entity("NguyenVanAn0025.Models.NVA025SanPham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasColumnType("TEXT");

                    b.Property<string>("GiaSanPham")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("TEXT");

                    b.HasKey("MaSanPham");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("NguyenVanAn0025.Models.NVA025New", b =>
                {
                    b.HasOne("NguyenVanAn0025.Models.NVA025SanPham", "NVA025SanPham")
                        .WithMany()
                        .HasForeignKey("TenSanPham");

                    b.Navigation("NVA025SanPham");
                });
#pragma warning restore 612, 618
        }
    }
}
